# -*- coding: utf-8 -*-
"""EDA_LAB01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bijWbxfIOvonbfO6fxwnsCYiqN6oJ-_J

\\

---

\\

**LINK GitHub (Distancias C++):** [*Lab_01_ADA_c++_2023B*](https://github.com/AngelNifla/EPCC_EDA_2023/tree/main/LAB) \\
\
**LINK Colab (Gráficas Python):** [*Lab01_ADA_python_2023B*](https://colab.research.google.com/drive/1bijWbxfIOvonbfO6fxwnsCYiqN6oJ-_J?usp=sharing) \\

\\

---

\\

**Implementacion de Codigo Python:**

En este apartado se realizan las gráficas de las distancias obtenidas:
"""

import matplotlib.pyplot as plt

############ Se ingresa las distancias del txt a un array.
dim = [10,50,100,500,1000,2000,5000]
Dat = []
for d in dim:
  txt = open('Distancias_Puntos_dimension_'+str(d)+'.txt')

  data = []
  for line in txt:
      line = line.rstrip()
      numero = ""
      for x in line:
          if x.find(','):
              numero += str(x)
          else:
              data.append(float(numero))
              numero = ""
  #print(data)
  l = len(data)
  Dat.append(data)
  print('-> Dimension: '+str(d)+', # Distancias calculadas: '+str(l))

############ Se crea el histograma
colors = ['green','blue','black','gray','red','orange','purple']
for s in range(7):
  print('\t-> Grafico '+str(s+1)+'\n')
  plt.title('Histograma de las distancias entre puntos con dimensión '+str(dim[s]))
  plt.xlabel('Distancia')
  plt.ylabel('Frecuencia')
  plt.hist(Dat[s], alpha=1, edgecolor = 'black',  linewidth=0.5, rwidth=0.9, color=str(colors[s]))
  plt.grid(True)
  plt.show()
  plt.clf()
  print('\n')

print('-> Graficos Generados con exito')